/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Locale } from "./models/locale";
import { Novl } from "./models/novl";
import { Breakpoints, Grid } from "./data/novl-carousel";
export { Locale } from "./models/locale";
export { Novl } from "./models/novl";
export { Breakpoints, Grid } from "./data/novl-carousel";
export namespace Components {
    interface UrAvatar {
        "border": string;
        "name"?: string;
        "radius": string;
        "size": string;
        "src": string;
    }
    interface UrButton {
        "disabled": boolean;
        "endIcon": any;
        "fullWidth": boolean;
        "icon": any;
        "variant": 'elevated' | 'filled' | 'tonal' | 'outlined' | 'text';
    }
    interface UrButtonArrowLeft {
    }
    interface UrButtonArrowRight {
    }
    interface UrButtonIcon {
        "disabled": boolean;
        "icon": string;
        "loading": boolean;
        "selected": boolean;
        "selectedIcon": string;
        "variant": 'standard' | 'filled' | 'tonal' | 'outlined';
    }
    interface UrCheckbox {
        "checked": boolean;
        "disabled": boolean;
    }
    interface UrChip {
        "backColor": string;
        "border": string;
        "disabled": boolean;
        "fontColor": string;
        "label": string;
        "loading": boolean;
        "radius": string;
        "size": string;
    }
    interface UrDialog {
        "borderRadius": string | null;
        "closeDialog": () => Promise<void>;
        "closeOnEsc": boolean;
        "closeOnOverlayClick": boolean;
        "description": string | null;
        "fullscreen": boolean;
        "open": boolean;
        "openDialog": () => Promise<void>;
    }
    interface UrHero {
        "backgroundAlignment": 'left' | 'center' | 'right';
        "backgroundColor": string;
        "backgroundImage": string;
        "backgroundJustification": 'top' | 'center' | 'bottom';
        "ctaText": string;
        "heroSubtitle": string;
        "heroSubtitleColor": string;
        "heroTitle": string;
        "heroTitleColor": string;
        "layout": 'left' | 'right' | 'center';
    }
    interface UrList {
    }
    interface UrListItem {
        "active": boolean;
        "alignment": 'start' | 'center' | 'end';
        "content"?: string;
        "description"?: string;
        "disabled": boolean;
        "endIcon"?: string;
        "href"?: string;
        "icon"?: string;
        "nonclickable": boolean;
        "rel"?: string;
        "rounded": boolean;
        "target"?: '_blank' | '_self' | '_parent' | '_top';
    }
    interface UrListSubheader {
        "text": string;
    }
    interface UrLoader {
    }
    interface UrLocaleFilterButton {
        "count": number;
        "selected": boolean;
    }
    interface UrLocaleFilterPanel {
        "disabledLocales": string[];
        /**
          * List of available languages
         */
        "locales": Array<Locale>;
        /**
          * Whether to show the footer
         */
        "showFooter": boolean;
        /**
          * Whether to show the header
         */
        "showHeader": boolean;
    }
    interface UrLogo {
        /**
          * Color of the logo
         */
        "color": string;
        /**
          * Height of the logo
         */
        "height": string;
        /**
          * Opacity of the logo
         */
        "opacity": number;
        /**
          * Rotation angle of the logo in degrees
         */
        "rotation": number;
        /**
          * Width of the logo
         */
        "width": string;
    }
    interface UrMainDesktopTopAppBar {
        "logoOpacity": number;
        "logoRotation": number;
        "searchText": string;
        "variant": string;
    }
    interface UrMainLeftMenu {
        "loggedIn": boolean;
        "userAvatar"?: string;
        "userName"?: string;
        "userRole"?: string;
    }
    interface UrMenuItem {
        "disabled": boolean;
        "label": string;
        "selected": boolean;
        "value": string;
    }
    interface UrMenuProfile {
        "userAvatar"?: string;
        "userName"?: string;
        "userRole"?: string;
    }
    interface UrNavigationDrawer {
        "closeDrawer": () => Promise<void>;
        /**
          * Closes the drawer when the 'Esc' key is pressed
         */
        "closeOnEsc": boolean;
        /**
          * Closes the drawer when clicking outside of it
         */
        "closeOnOverlayClick": boolean;
        /**
          * Contains the drawer within its parent element
         */
        "contained": boolean;
        /**
          * Determines if the drawer is open
         */
        "open": boolean;
        "openDrawer": () => Promise<void>;
        /**
          * Placement of the drawer: 'left' or 'right'
         */
        "placement": 'left' | 'right';
    }
    interface UrNovl {
        "authorAvatar": any;
        "authorName": any;
        "likes": number;
        "loading": boolean;
        "novlCover": any;
        "novlCoverFallback": string;
        "novlDescription": any;
        "novlId": any;
        "novlTitle": string;
        "price": string | null;
        "published": boolean;
        "publisherAvatar": string | null;
        "publisherName": string | null;
        "showStats": boolean;
        "views": number;
    }
    interface UrNovlCarousel {
        "breakpoints"?: Breakpoints;
        "grid"?: Grid;
        "navigation"?: boolean;
        "novls": Array<Novl>;
        "slidesPerView"?: number | 'auto';
        "spaceBetween"?: number | string;
    }
    interface UrPage {
        "followers": number;
        "pageCover": any;
        "pageCoverFallback": string;
        "pageDescription": any;
        "pageTitle": string;
        "showStats": boolean;
    }
    interface UrPageProfile {
        "avatar": any;
        "description": any;
        "email": any;
        "facebook_url": any;
        "followers": number | null;
        "following": number | null;
        "genres": string | null;
        "languages": string | null;
        "linkedin_url": any;
        "literatureTypes": string | null;
        "location": any;
        "members": number | null;
        "name": any;
        "pageCreationDate": any;
        "pageCreatorImage": any;
        "pageCreatorName": any;
        "phone": any;
        "showBecomeMember": boolean;
        "showDonate": boolean;
        "showFollow": boolean;
        "showSendMessage": boolean;
        "stories": number | null;
        "twitter_url": any;
        "views": number | null;
        "website": any;
    }
    interface UrProfile {
        "description": any;
        "email": any;
        "facebook_url": any;
        "followers_count": number;
        "genres": string;
        "languages": string;
        "linkedin_url": any;
        "location": any;
        "member_since": string;
        "name": any;
        "phone": any;
        "show_become_member": boolean;
        "show_donate": boolean;
        "show_follow": boolean;
        "show_genres": boolean;
        "show_languages": boolean;
        "show_member_since": boolean;
        "show_send_message": boolean;
        "show_stats": boolean;
        "stories_count": number;
        "twitter_url": any;
        "views_count": number;
        "website": any;
        "writers_count": number;
    }
    interface UrRadioButton {
        "checked": boolean;
        "disabled": boolean;
        "text": string;
    }
    interface UrReadMobileTopAppBar {
        "headerTitle": string;
        "scrollBehavior": 'hide' | 'shrink' | 'elevate';
        "scrollThreshold": number;
        "variant": string;
    }
    interface UrSegmentButton {
        "likeLabel": string;
    }
    interface UrSelect {
        "clearable": boolean;
        "disabled": boolean;
        "endAligned": boolean;
        "endIcon": string;
        "form": string;
        "helper": string;
        "icon": string;
        "items": Array<[label: string, value: string, disabled: boolean]>;
        "label": string;
        "multiple": boolean;
        "name": string;
        "placeholder": string;
        "placement": 'auto' | 'bottom' | 'top';
        "readonly": boolean;
        "value": string | string[];
        "variant": 'filled' | 'outlined';
    }
    interface UrSwitch {
        "checked": boolean;
        "disabled": boolean;
    }
    interface UrTabs {
        "panels": { content: string, value: string }[];
        "tabs": { label: string, value: string }[];
    }
    interface UrTextField {
        "disabled": boolean;
        "endIcon": any;
        "helper": string | null;
        "label": string;
        "placeholder": string | null;
        "value": string;
        "variant": 'filled' | 'outlined';
    }
    interface UrTopAppBar {
        "headerTitle": string;
        "logoOpacity": number;
        "logoRotation": number;
        "scrollBehavior": 'hide' | 'shrink' | 'elevate';
        "scrollThreshold": number;
        "variant": string;
    }
    interface UrUser {
        "followers": number;
        "showStats": boolean;
        "userCover": any;
        "userCoverFallback": string;
        "userDescription": any;
        "userTitle": string;
    }
    interface UrUserProfile {
    }
}
export interface UrButtonArrowLeftCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrButtonArrowLeftElement;
}
export interface UrButtonArrowRightCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrButtonArrowRightElement;
}
export interface UrHeroCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrHeroElement;
}
export interface UrLocaleFilterPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrLocaleFilterPanelElement;
}
export interface UrMainDesktopTopAppBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrMainDesktopTopAppBarElement;
}
export interface UrMainLeftMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrMainLeftMenuElement;
}
export interface UrMenuItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrMenuItemElement;
}
export interface UrNovlCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrNovlElement;
}
export interface UrNovlCarouselCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrNovlCarouselElement;
}
export interface UrPageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrPageElement;
}
export interface UrPageProfileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrPageProfileElement;
}
export interface UrReadMobileTopAppBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrReadMobileTopAppBarElement;
}
export interface UrSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrSelectElement;
}
export interface UrUserCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrUserElement;
}
declare global {
    interface HTMLUrAvatarElement extends Components.UrAvatar, HTMLStencilElement {
    }
    var HTMLUrAvatarElement: {
        prototype: HTMLUrAvatarElement;
        new (): HTMLUrAvatarElement;
    };
    interface HTMLUrButtonElement extends Components.UrButton, HTMLStencilElement {
    }
    var HTMLUrButtonElement: {
        prototype: HTMLUrButtonElement;
        new (): HTMLUrButtonElement;
    };
    interface HTMLUrButtonArrowLeftElementEventMap {
        "leftClicked": any;
    }
    interface HTMLUrButtonArrowLeftElement extends Components.UrButtonArrowLeft, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrButtonArrowLeftElementEventMap>(type: K, listener: (this: HTMLUrButtonArrowLeftElement, ev: UrButtonArrowLeftCustomEvent<HTMLUrButtonArrowLeftElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrButtonArrowLeftElementEventMap>(type: K, listener: (this: HTMLUrButtonArrowLeftElement, ev: UrButtonArrowLeftCustomEvent<HTMLUrButtonArrowLeftElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrButtonArrowLeftElement: {
        prototype: HTMLUrButtonArrowLeftElement;
        new (): HTMLUrButtonArrowLeftElement;
    };
    interface HTMLUrButtonArrowRightElementEventMap {
        "rightClicked": any;
    }
    interface HTMLUrButtonArrowRightElement extends Components.UrButtonArrowRight, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrButtonArrowRightElementEventMap>(type: K, listener: (this: HTMLUrButtonArrowRightElement, ev: UrButtonArrowRightCustomEvent<HTMLUrButtonArrowRightElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrButtonArrowRightElementEventMap>(type: K, listener: (this: HTMLUrButtonArrowRightElement, ev: UrButtonArrowRightCustomEvent<HTMLUrButtonArrowRightElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrButtonArrowRightElement: {
        prototype: HTMLUrButtonArrowRightElement;
        new (): HTMLUrButtonArrowRightElement;
    };
    interface HTMLUrButtonIconElement extends Components.UrButtonIcon, HTMLStencilElement {
    }
    var HTMLUrButtonIconElement: {
        prototype: HTMLUrButtonIconElement;
        new (): HTMLUrButtonIconElement;
    };
    interface HTMLUrCheckboxElement extends Components.UrCheckbox, HTMLStencilElement {
    }
    var HTMLUrCheckboxElement: {
        prototype: HTMLUrCheckboxElement;
        new (): HTMLUrCheckboxElement;
    };
    interface HTMLUrChipElement extends Components.UrChip, HTMLStencilElement {
    }
    var HTMLUrChipElement: {
        prototype: HTMLUrChipElement;
        new (): HTMLUrChipElement;
    };
    interface HTMLUrDialogElement extends Components.UrDialog, HTMLStencilElement {
    }
    var HTMLUrDialogElement: {
        prototype: HTMLUrDialogElement;
        new (): HTMLUrDialogElement;
    };
    interface HTMLUrHeroElementEventMap {
        "ctaClicked": void;
    }
    interface HTMLUrHeroElement extends Components.UrHero, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrHeroElementEventMap>(type: K, listener: (this: HTMLUrHeroElement, ev: UrHeroCustomEvent<HTMLUrHeroElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrHeroElementEventMap>(type: K, listener: (this: HTMLUrHeroElement, ev: UrHeroCustomEvent<HTMLUrHeroElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrHeroElement: {
        prototype: HTMLUrHeroElement;
        new (): HTMLUrHeroElement;
    };
    interface HTMLUrListElement extends Components.UrList, HTMLStencilElement {
    }
    var HTMLUrListElement: {
        prototype: HTMLUrListElement;
        new (): HTMLUrListElement;
    };
    interface HTMLUrListItemElement extends Components.UrListItem, HTMLStencilElement {
    }
    var HTMLUrListItemElement: {
        prototype: HTMLUrListItemElement;
        new (): HTMLUrListItemElement;
    };
    interface HTMLUrListSubheaderElement extends Components.UrListSubheader, HTMLStencilElement {
    }
    var HTMLUrListSubheaderElement: {
        prototype: HTMLUrListSubheaderElement;
        new (): HTMLUrListSubheaderElement;
    };
    interface HTMLUrLoaderElement extends Components.UrLoader, HTMLStencilElement {
    }
    var HTMLUrLoaderElement: {
        prototype: HTMLUrLoaderElement;
        new (): HTMLUrLoaderElement;
    };
    interface HTMLUrLocaleFilterButtonElement extends Components.UrLocaleFilterButton, HTMLStencilElement {
    }
    var HTMLUrLocaleFilterButtonElement: {
        prototype: HTMLUrLocaleFilterButtonElement;
        new (): HTMLUrLocaleFilterButtonElement;
    };
    interface HTMLUrLocaleFilterPanelElementEventMap {
        "save": Array<Locale>;
        "cancel": void;
    }
    interface HTMLUrLocaleFilterPanelElement extends Components.UrLocaleFilterPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrLocaleFilterPanelElementEventMap>(type: K, listener: (this: HTMLUrLocaleFilterPanelElement, ev: UrLocaleFilterPanelCustomEvent<HTMLUrLocaleFilterPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrLocaleFilterPanelElementEventMap>(type: K, listener: (this: HTMLUrLocaleFilterPanelElement, ev: UrLocaleFilterPanelCustomEvent<HTMLUrLocaleFilterPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrLocaleFilterPanelElement: {
        prototype: HTMLUrLocaleFilterPanelElement;
        new (): HTMLUrLocaleFilterPanelElement;
    };
    interface HTMLUrLogoElement extends Components.UrLogo, HTMLStencilElement {
    }
    var HTMLUrLogoElement: {
        prototype: HTMLUrLogoElement;
        new (): HTMLUrLogoElement;
    };
    interface HTMLUrMainDesktopTopAppBarElementEventMap {
        "searchLinkClicked": void;
    }
    interface HTMLUrMainDesktopTopAppBarElement extends Components.UrMainDesktopTopAppBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrMainDesktopTopAppBarElementEventMap>(type: K, listener: (this: HTMLUrMainDesktopTopAppBarElement, ev: UrMainDesktopTopAppBarCustomEvent<HTMLUrMainDesktopTopAppBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrMainDesktopTopAppBarElementEventMap>(type: K, listener: (this: HTMLUrMainDesktopTopAppBarElement, ev: UrMainDesktopTopAppBarCustomEvent<HTMLUrMainDesktopTopAppBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrMainDesktopTopAppBarElement: {
        prototype: HTMLUrMainDesktopTopAppBarElement;
        new (): HTMLUrMainDesktopTopAppBarElement;
    };
    interface HTMLUrMainLeftMenuElementEventMap {
        "toggleExpand": boolean;
    }
    interface HTMLUrMainLeftMenuElement extends Components.UrMainLeftMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrMainLeftMenuElementEventMap>(type: K, listener: (this: HTMLUrMainLeftMenuElement, ev: UrMainLeftMenuCustomEvent<HTMLUrMainLeftMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrMainLeftMenuElementEventMap>(type: K, listener: (this: HTMLUrMainLeftMenuElement, ev: UrMainLeftMenuCustomEvent<HTMLUrMainLeftMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrMainLeftMenuElement: {
        prototype: HTMLUrMainLeftMenuElement;
        new (): HTMLUrMainLeftMenuElement;
    };
    interface HTMLUrMenuItemElementEventMap {
        "itemClicked": string;
    }
    interface HTMLUrMenuItemElement extends Components.UrMenuItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrMenuItemElementEventMap>(type: K, listener: (this: HTMLUrMenuItemElement, ev: UrMenuItemCustomEvent<HTMLUrMenuItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrMenuItemElementEventMap>(type: K, listener: (this: HTMLUrMenuItemElement, ev: UrMenuItemCustomEvent<HTMLUrMenuItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrMenuItemElement: {
        prototype: HTMLUrMenuItemElement;
        new (): HTMLUrMenuItemElement;
    };
    interface HTMLUrMenuProfileElement extends Components.UrMenuProfile, HTMLStencilElement {
    }
    var HTMLUrMenuProfileElement: {
        prototype: HTMLUrMenuProfileElement;
        new (): HTMLUrMenuProfileElement;
    };
    interface HTMLUrNavigationDrawerElement extends Components.UrNavigationDrawer, HTMLStencilElement {
    }
    var HTMLUrNavigationDrawerElement: {
        prototype: HTMLUrNavigationDrawerElement;
        new (): HTMLUrNavigationDrawerElement;
    };
    interface HTMLUrNovlElementEventMap {
        "novlClicked": string;
    }
    interface HTMLUrNovlElement extends Components.UrNovl, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrNovlElementEventMap>(type: K, listener: (this: HTMLUrNovlElement, ev: UrNovlCustomEvent<HTMLUrNovlElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrNovlElementEventMap>(type: K, listener: (this: HTMLUrNovlElement, ev: UrNovlCustomEvent<HTMLUrNovlElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrNovlElement: {
        prototype: HTMLUrNovlElement;
        new (): HTMLUrNovlElement;
    };
    interface HTMLUrNovlCarouselElementEventMap {
        "intersectionUpdated": Array<IntersectionObserverEntry>;
        "prevClicked": void;
        "nextClicked": void;
    }
    interface HTMLUrNovlCarouselElement extends Components.UrNovlCarousel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrNovlCarouselElementEventMap>(type: K, listener: (this: HTMLUrNovlCarouselElement, ev: UrNovlCarouselCustomEvent<HTMLUrNovlCarouselElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrNovlCarouselElementEventMap>(type: K, listener: (this: HTMLUrNovlCarouselElement, ev: UrNovlCarouselCustomEvent<HTMLUrNovlCarouselElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrNovlCarouselElement: {
        prototype: HTMLUrNovlCarouselElement;
        new (): HTMLUrNovlCarouselElement;
    };
    interface HTMLUrPageElementEventMap {
        "pageFollowClicked": any;
    }
    interface HTMLUrPageElement extends Components.UrPage, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrPageElementEventMap>(type: K, listener: (this: HTMLUrPageElement, ev: UrPageCustomEvent<HTMLUrPageElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrPageElementEventMap>(type: K, listener: (this: HTMLUrPageElement, ev: UrPageCustomEvent<HTMLUrPageElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrPageElement: {
        prototype: HTMLUrPageElement;
        new (): HTMLUrPageElement;
    };
    interface HTMLUrPageProfileElementEventMap {
        "follow": any;
        "member": any;
        "donate": any;
        "sendMessage": any;
    }
    interface HTMLUrPageProfileElement extends Components.UrPageProfile, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrPageProfileElementEventMap>(type: K, listener: (this: HTMLUrPageProfileElement, ev: UrPageProfileCustomEvent<HTMLUrPageProfileElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrPageProfileElementEventMap>(type: K, listener: (this: HTMLUrPageProfileElement, ev: UrPageProfileCustomEvent<HTMLUrPageProfileElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrPageProfileElement: {
        prototype: HTMLUrPageProfileElement;
        new (): HTMLUrPageProfileElement;
    };
    interface HTMLUrProfileElement extends Components.UrProfile, HTMLStencilElement {
    }
    var HTMLUrProfileElement: {
        prototype: HTMLUrProfileElement;
        new (): HTMLUrProfileElement;
    };
    interface HTMLUrRadioButtonElement extends Components.UrRadioButton, HTMLStencilElement {
    }
    var HTMLUrRadioButtonElement: {
        prototype: HTMLUrRadioButtonElement;
        new (): HTMLUrRadioButtonElement;
    };
    interface HTMLUrReadMobileTopAppBarElementEventMap {
        "backClick": void;
        "chaptersClick": void;
        "readingSettingsClick": void;
    }
    interface HTMLUrReadMobileTopAppBarElement extends Components.UrReadMobileTopAppBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrReadMobileTopAppBarElementEventMap>(type: K, listener: (this: HTMLUrReadMobileTopAppBarElement, ev: UrReadMobileTopAppBarCustomEvent<HTMLUrReadMobileTopAppBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrReadMobileTopAppBarElementEventMap>(type: K, listener: (this: HTMLUrReadMobileTopAppBarElement, ev: UrReadMobileTopAppBarCustomEvent<HTMLUrReadMobileTopAppBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrReadMobileTopAppBarElement: {
        prototype: HTMLUrReadMobileTopAppBarElement;
        new (): HTMLUrReadMobileTopAppBarElement;
    };
    interface HTMLUrSegmentButtonElement extends Components.UrSegmentButton, HTMLStencilElement {
    }
    var HTMLUrSegmentButtonElement: {
        prototype: HTMLUrSegmentButtonElement;
        new (): HTMLUrSegmentButtonElement;
    };
    interface HTMLUrSelectElementEventMap {
        "itemClicked": string | string[];
    }
    interface HTMLUrSelectElement extends Components.UrSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrSelectElementEventMap>(type: K, listener: (this: HTMLUrSelectElement, ev: UrSelectCustomEvent<HTMLUrSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrSelectElementEventMap>(type: K, listener: (this: HTMLUrSelectElement, ev: UrSelectCustomEvent<HTMLUrSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrSelectElement: {
        prototype: HTMLUrSelectElement;
        new (): HTMLUrSelectElement;
    };
    interface HTMLUrSwitchElement extends Components.UrSwitch, HTMLStencilElement {
    }
    var HTMLUrSwitchElement: {
        prototype: HTMLUrSwitchElement;
        new (): HTMLUrSwitchElement;
    };
    interface HTMLUrTabsElement extends Components.UrTabs, HTMLStencilElement {
    }
    var HTMLUrTabsElement: {
        prototype: HTMLUrTabsElement;
        new (): HTMLUrTabsElement;
    };
    interface HTMLUrTextFieldElement extends Components.UrTextField, HTMLStencilElement {
    }
    var HTMLUrTextFieldElement: {
        prototype: HTMLUrTextFieldElement;
        new (): HTMLUrTextFieldElement;
    };
    interface HTMLUrTopAppBarElement extends Components.UrTopAppBar, HTMLStencilElement {
    }
    var HTMLUrTopAppBarElement: {
        prototype: HTMLUrTopAppBarElement;
        new (): HTMLUrTopAppBarElement;
    };
    interface HTMLUrUserElementEventMap {
        "userFollowClicked": any;
    }
    interface HTMLUrUserElement extends Components.UrUser, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrUserElementEventMap>(type: K, listener: (this: HTMLUrUserElement, ev: UrUserCustomEvent<HTMLUrUserElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrUserElementEventMap>(type: K, listener: (this: HTMLUrUserElement, ev: UrUserCustomEvent<HTMLUrUserElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrUserElement: {
        prototype: HTMLUrUserElement;
        new (): HTMLUrUserElement;
    };
    interface HTMLUrUserProfileElement extends Components.UrUserProfile, HTMLStencilElement {
    }
    var HTMLUrUserProfileElement: {
        prototype: HTMLUrUserProfileElement;
        new (): HTMLUrUserProfileElement;
    };
    interface HTMLElementTagNameMap {
        "ur-avatar": HTMLUrAvatarElement;
        "ur-button": HTMLUrButtonElement;
        "ur-button-arrow-left": HTMLUrButtonArrowLeftElement;
        "ur-button-arrow-right": HTMLUrButtonArrowRightElement;
        "ur-button-icon": HTMLUrButtonIconElement;
        "ur-checkbox": HTMLUrCheckboxElement;
        "ur-chip": HTMLUrChipElement;
        "ur-dialog": HTMLUrDialogElement;
        "ur-hero": HTMLUrHeroElement;
        "ur-list": HTMLUrListElement;
        "ur-list-item": HTMLUrListItemElement;
        "ur-list-subheader": HTMLUrListSubheaderElement;
        "ur-loader": HTMLUrLoaderElement;
        "ur-locale-filter-button": HTMLUrLocaleFilterButtonElement;
        "ur-locale-filter-panel": HTMLUrLocaleFilterPanelElement;
        "ur-logo": HTMLUrLogoElement;
        "ur-main-desktop-top-app-bar": HTMLUrMainDesktopTopAppBarElement;
        "ur-main-left-menu": HTMLUrMainLeftMenuElement;
        "ur-menu-item": HTMLUrMenuItemElement;
        "ur-menu-profile": HTMLUrMenuProfileElement;
        "ur-navigation-drawer": HTMLUrNavigationDrawerElement;
        "ur-novl": HTMLUrNovlElement;
        "ur-novl-carousel": HTMLUrNovlCarouselElement;
        "ur-page": HTMLUrPageElement;
        "ur-page-profile": HTMLUrPageProfileElement;
        "ur-profile": HTMLUrProfileElement;
        "ur-radio-button": HTMLUrRadioButtonElement;
        "ur-read-mobile-top-app-bar": HTMLUrReadMobileTopAppBarElement;
        "ur-segment-button": HTMLUrSegmentButtonElement;
        "ur-select": HTMLUrSelectElement;
        "ur-switch": HTMLUrSwitchElement;
        "ur-tabs": HTMLUrTabsElement;
        "ur-text-field": HTMLUrTextFieldElement;
        "ur-top-app-bar": HTMLUrTopAppBarElement;
        "ur-user": HTMLUrUserElement;
        "ur-user-profile": HTMLUrUserProfileElement;
    }
}
declare namespace LocalJSX {
    interface UrAvatar {
        "border"?: string;
        "name"?: string;
        "radius"?: string;
        "size"?: string;
        "src"?: string;
    }
    interface UrButton {
        "disabled"?: boolean;
        "endIcon"?: any;
        "fullWidth"?: boolean;
        "icon"?: any;
        "variant"?: 'elevated' | 'filled' | 'tonal' | 'outlined' | 'text';
    }
    interface UrButtonArrowLeft {
        "onLeftClicked"?: (event: UrButtonArrowLeftCustomEvent<any>) => void;
    }
    interface UrButtonArrowRight {
        "onRightClicked"?: (event: UrButtonArrowRightCustomEvent<any>) => void;
    }
    interface UrButtonIcon {
        "disabled"?: boolean;
        "icon"?: string;
        "loading"?: boolean;
        "selected"?: boolean;
        "selectedIcon"?: string;
        "variant"?: 'standard' | 'filled' | 'tonal' | 'outlined';
    }
    interface UrCheckbox {
        "checked"?: boolean;
        "disabled"?: boolean;
    }
    interface UrChip {
        "backColor"?: string;
        "border"?: string;
        "disabled"?: boolean;
        "fontColor"?: string;
        "label"?: string;
        "loading"?: boolean;
        "radius"?: string;
        "size"?: string;
    }
    interface UrDialog {
        "borderRadius"?: string | null;
        "closeOnEsc"?: boolean;
        "closeOnOverlayClick"?: boolean;
        "description"?: string | null;
        "fullscreen"?: boolean;
        "open"?: boolean;
    }
    interface UrHero {
        "backgroundAlignment"?: 'left' | 'center' | 'right';
        "backgroundColor"?: string;
        "backgroundImage"?: string;
        "backgroundJustification"?: 'top' | 'center' | 'bottom';
        "ctaText"?: string;
        "heroSubtitle"?: string;
        "heroSubtitleColor"?: string;
        "heroTitle"?: string;
        "heroTitleColor"?: string;
        "layout"?: 'left' | 'right' | 'center';
        "onCtaClicked"?: (event: UrHeroCustomEvent<void>) => void;
    }
    interface UrList {
    }
    interface UrListItem {
        "active"?: boolean;
        "alignment"?: 'start' | 'center' | 'end';
        "content"?: string;
        "description"?: string;
        "disabled"?: boolean;
        "endIcon"?: string;
        "href"?: string;
        "icon"?: string;
        "nonclickable"?: boolean;
        "rel"?: string;
        "rounded"?: boolean;
        "target"?: '_blank' | '_self' | '_parent' | '_top';
    }
    interface UrListSubheader {
        "text"?: string;
    }
    interface UrLoader {
    }
    interface UrLocaleFilterButton {
        "count"?: number;
        "selected"?: boolean;
    }
    interface UrLocaleFilterPanel {
        "disabledLocales"?: string[];
        /**
          * List of available languages
         */
        "locales"?: Array<Locale>;
        /**
          * Event emitted when canceling
         */
        "onCancel"?: (event: UrLocaleFilterPanelCustomEvent<void>) => void;
        /**
          * Event emitted when saving languages
         */
        "onSave"?: (event: UrLocaleFilterPanelCustomEvent<Array<Locale>>) => void;
        /**
          * Whether to show the footer
         */
        "showFooter"?: boolean;
        /**
          * Whether to show the header
         */
        "showHeader"?: boolean;
    }
    interface UrLogo {
        /**
          * Color of the logo
         */
        "color"?: string;
        /**
          * Height of the logo
         */
        "height"?: string;
        /**
          * Opacity of the logo
         */
        "opacity"?: number;
        /**
          * Rotation angle of the logo in degrees
         */
        "rotation"?: number;
        /**
          * Width of the logo
         */
        "width"?: string;
    }
    interface UrMainDesktopTopAppBar {
        "logoOpacity"?: number;
        "logoRotation"?: number;
        "onSearchLinkClicked"?: (event: UrMainDesktopTopAppBarCustomEvent<void>) => void;
        "searchText"?: string;
        "variant"?: string;
    }
    interface UrMainLeftMenu {
        "loggedIn"?: boolean;
        "onToggleExpand"?: (event: UrMainLeftMenuCustomEvent<boolean>) => void;
        "userAvatar"?: string;
        "userName"?: string;
        "userRole"?: string;
    }
    interface UrMenuItem {
        "disabled"?: boolean;
        "label"?: string;
        "onItemClicked"?: (event: UrMenuItemCustomEvent<string>) => void;
        "selected"?: boolean;
        "value"?: string;
    }
    interface UrMenuProfile {
        "userAvatar"?: string;
        "userName"?: string;
        "userRole"?: string;
    }
    interface UrNavigationDrawer {
        /**
          * Closes the drawer when the 'Esc' key is pressed
         */
        "closeOnEsc"?: boolean;
        /**
          * Closes the drawer when clicking outside of it
         */
        "closeOnOverlayClick"?: boolean;
        /**
          * Contains the drawer within its parent element
         */
        "contained"?: boolean;
        /**
          * Determines if the drawer is open
         */
        "open"?: boolean;
        /**
          * Placement of the drawer: 'left' or 'right'
         */
        "placement"?: 'left' | 'right';
    }
    interface UrNovl {
        "authorAvatar"?: any;
        "authorName"?: any;
        "likes"?: number;
        "loading"?: boolean;
        "novlCover"?: any;
        "novlCoverFallback"?: string;
        "novlDescription"?: any;
        "novlId"?: any;
        "novlTitle"?: string;
        "onNovlClicked"?: (event: UrNovlCustomEvent<string>) => void;
        "price"?: string | null;
        "published"?: boolean;
        "publisherAvatar"?: string | null;
        "publisherName"?: string | null;
        "showStats"?: boolean;
        "views"?: number;
    }
    interface UrNovlCarousel {
        "breakpoints"?: Breakpoints;
        "grid"?: Grid;
        "navigation"?: boolean;
        "novls"?: Array<Novl>;
        "onIntersectionUpdated"?: (event: UrNovlCarouselCustomEvent<Array<IntersectionObserverEntry>>) => void;
        "onNextClicked"?: (event: UrNovlCarouselCustomEvent<void>) => void;
        "onPrevClicked"?: (event: UrNovlCarouselCustomEvent<void>) => void;
        "slidesPerView"?: number | 'auto';
        "spaceBetween"?: number | string;
    }
    interface UrPage {
        "followers"?: number;
        "onPageFollowClicked"?: (event: UrPageCustomEvent<any>) => void;
        "pageCover"?: any;
        "pageCoverFallback"?: string;
        "pageDescription"?: any;
        "pageTitle"?: string;
        "showStats"?: boolean;
    }
    interface UrPageProfile {
        "avatar"?: any;
        "description"?: any;
        "email"?: any;
        "facebook_url"?: any;
        "followers"?: number | null;
        "following"?: number | null;
        "genres"?: string | null;
        "languages"?: string | null;
        "linkedin_url"?: any;
        "literatureTypes"?: string | null;
        "location"?: any;
        "members"?: number | null;
        "name"?: any;
        "onDonate"?: (event: UrPageProfileCustomEvent<any>) => void;
        "onFollow"?: (event: UrPageProfileCustomEvent<any>) => void;
        "onMember"?: (event: UrPageProfileCustomEvent<any>) => void;
        "onSendMessage"?: (event: UrPageProfileCustomEvent<any>) => void;
        "pageCreationDate"?: any;
        "pageCreatorImage"?: any;
        "pageCreatorName"?: any;
        "phone"?: any;
        "showBecomeMember"?: boolean;
        "showDonate"?: boolean;
        "showFollow"?: boolean;
        "showSendMessage"?: boolean;
        "stories"?: number | null;
        "twitter_url"?: any;
        "views"?: number | null;
        "website"?: any;
    }
    interface UrProfile {
        "description"?: any;
        "email"?: any;
        "facebook_url"?: any;
        "followers_count"?: number;
        "genres"?: string;
        "languages"?: string;
        "linkedin_url"?: any;
        "location"?: any;
        "member_since"?: string;
        "name"?: any;
        "phone"?: any;
        "show_become_member"?: boolean;
        "show_donate"?: boolean;
        "show_follow"?: boolean;
        "show_genres"?: boolean;
        "show_languages"?: boolean;
        "show_member_since"?: boolean;
        "show_send_message"?: boolean;
        "show_stats"?: boolean;
        "stories_count"?: number;
        "twitter_url"?: any;
        "views_count"?: number;
        "website"?: any;
        "writers_count"?: number;
    }
    interface UrRadioButton {
        "checked"?: boolean;
        "disabled"?: boolean;
        "text"?: string;
    }
    interface UrReadMobileTopAppBar {
        "headerTitle"?: string;
        "onBackClick"?: (event: UrReadMobileTopAppBarCustomEvent<void>) => void;
        "onChaptersClick"?: (event: UrReadMobileTopAppBarCustomEvent<void>) => void;
        "onReadingSettingsClick"?: (event: UrReadMobileTopAppBarCustomEvent<void>) => void;
        "scrollBehavior"?: 'hide' | 'shrink' | 'elevate';
        "scrollThreshold"?: number;
        "variant"?: string;
    }
    interface UrSegmentButton {
        "likeLabel"?: string;
    }
    interface UrSelect {
        "clearable"?: boolean;
        "disabled"?: boolean;
        "endAligned"?: boolean;
        "endIcon"?: string;
        "form"?: string;
        "helper"?: string;
        "icon"?: string;
        "items"?: Array<[label: string, value: string, disabled: boolean]>;
        "label"?: string;
        "multiple"?: boolean;
        "name"?: string;
        "onItemClicked"?: (event: UrSelectCustomEvent<string | string[]>) => void;
        "placeholder"?: string;
        "placement"?: 'auto' | 'bottom' | 'top';
        "readonly"?: boolean;
        "value"?: string | string[];
        "variant"?: 'filled' | 'outlined';
    }
    interface UrSwitch {
        "checked"?: boolean;
        "disabled"?: boolean;
    }
    interface UrTabs {
        "panels"?: { content: string, value: string }[];
        "tabs"?: { label: string, value: string }[];
    }
    interface UrTextField {
        "disabled"?: boolean;
        "endIcon"?: any;
        "helper"?: string | null;
        "label"?: string;
        "placeholder"?: string | null;
        "value"?: string;
        "variant"?: 'filled' | 'outlined';
    }
    interface UrTopAppBar {
        "headerTitle"?: string;
        "logoOpacity"?: number;
        "logoRotation"?: number;
        "scrollBehavior"?: 'hide' | 'shrink' | 'elevate';
        "scrollThreshold"?: number;
        "variant"?: string;
    }
    interface UrUser {
        "followers"?: number;
        "onUserFollowClicked"?: (event: UrUserCustomEvent<any>) => void;
        "showStats"?: boolean;
        "userCover"?: any;
        "userCoverFallback"?: string;
        "userDescription"?: any;
        "userTitle"?: string;
    }
    interface UrUserProfile {
    }
    interface IntrinsicElements {
        "ur-avatar": UrAvatar;
        "ur-button": UrButton;
        "ur-button-arrow-left": UrButtonArrowLeft;
        "ur-button-arrow-right": UrButtonArrowRight;
        "ur-button-icon": UrButtonIcon;
        "ur-checkbox": UrCheckbox;
        "ur-chip": UrChip;
        "ur-dialog": UrDialog;
        "ur-hero": UrHero;
        "ur-list": UrList;
        "ur-list-item": UrListItem;
        "ur-list-subheader": UrListSubheader;
        "ur-loader": UrLoader;
        "ur-locale-filter-button": UrLocaleFilterButton;
        "ur-locale-filter-panel": UrLocaleFilterPanel;
        "ur-logo": UrLogo;
        "ur-main-desktop-top-app-bar": UrMainDesktopTopAppBar;
        "ur-main-left-menu": UrMainLeftMenu;
        "ur-menu-item": UrMenuItem;
        "ur-menu-profile": UrMenuProfile;
        "ur-navigation-drawer": UrNavigationDrawer;
        "ur-novl": UrNovl;
        "ur-novl-carousel": UrNovlCarousel;
        "ur-page": UrPage;
        "ur-page-profile": UrPageProfile;
        "ur-profile": UrProfile;
        "ur-radio-button": UrRadioButton;
        "ur-read-mobile-top-app-bar": UrReadMobileTopAppBar;
        "ur-segment-button": UrSegmentButton;
        "ur-select": UrSelect;
        "ur-switch": UrSwitch;
        "ur-tabs": UrTabs;
        "ur-text-field": UrTextField;
        "ur-top-app-bar": UrTopAppBar;
        "ur-user": UrUser;
        "ur-user-profile": UrUserProfile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ur-avatar": LocalJSX.UrAvatar & JSXBase.HTMLAttributes<HTMLUrAvatarElement>;
            "ur-button": LocalJSX.UrButton & JSXBase.HTMLAttributes<HTMLUrButtonElement>;
            "ur-button-arrow-left": LocalJSX.UrButtonArrowLeft & JSXBase.HTMLAttributes<HTMLUrButtonArrowLeftElement>;
            "ur-button-arrow-right": LocalJSX.UrButtonArrowRight & JSXBase.HTMLAttributes<HTMLUrButtonArrowRightElement>;
            "ur-button-icon": LocalJSX.UrButtonIcon & JSXBase.HTMLAttributes<HTMLUrButtonIconElement>;
            "ur-checkbox": LocalJSX.UrCheckbox & JSXBase.HTMLAttributes<HTMLUrCheckboxElement>;
            "ur-chip": LocalJSX.UrChip & JSXBase.HTMLAttributes<HTMLUrChipElement>;
            "ur-dialog": LocalJSX.UrDialog & JSXBase.HTMLAttributes<HTMLUrDialogElement>;
            "ur-hero": LocalJSX.UrHero & JSXBase.HTMLAttributes<HTMLUrHeroElement>;
            "ur-list": LocalJSX.UrList & JSXBase.HTMLAttributes<HTMLUrListElement>;
            "ur-list-item": LocalJSX.UrListItem & JSXBase.HTMLAttributes<HTMLUrListItemElement>;
            "ur-list-subheader": LocalJSX.UrListSubheader & JSXBase.HTMLAttributes<HTMLUrListSubheaderElement>;
            "ur-loader": LocalJSX.UrLoader & JSXBase.HTMLAttributes<HTMLUrLoaderElement>;
            "ur-locale-filter-button": LocalJSX.UrLocaleFilterButton & JSXBase.HTMLAttributes<HTMLUrLocaleFilterButtonElement>;
            "ur-locale-filter-panel": LocalJSX.UrLocaleFilterPanel & JSXBase.HTMLAttributes<HTMLUrLocaleFilterPanelElement>;
            "ur-logo": LocalJSX.UrLogo & JSXBase.HTMLAttributes<HTMLUrLogoElement>;
            "ur-main-desktop-top-app-bar": LocalJSX.UrMainDesktopTopAppBar & JSXBase.HTMLAttributes<HTMLUrMainDesktopTopAppBarElement>;
            "ur-main-left-menu": LocalJSX.UrMainLeftMenu & JSXBase.HTMLAttributes<HTMLUrMainLeftMenuElement>;
            "ur-menu-item": LocalJSX.UrMenuItem & JSXBase.HTMLAttributes<HTMLUrMenuItemElement>;
            "ur-menu-profile": LocalJSX.UrMenuProfile & JSXBase.HTMLAttributes<HTMLUrMenuProfileElement>;
            "ur-navigation-drawer": LocalJSX.UrNavigationDrawer & JSXBase.HTMLAttributes<HTMLUrNavigationDrawerElement>;
            "ur-novl": LocalJSX.UrNovl & JSXBase.HTMLAttributes<HTMLUrNovlElement>;
            "ur-novl-carousel": LocalJSX.UrNovlCarousel & JSXBase.HTMLAttributes<HTMLUrNovlCarouselElement>;
            "ur-page": LocalJSX.UrPage & JSXBase.HTMLAttributes<HTMLUrPageElement>;
            "ur-page-profile": LocalJSX.UrPageProfile & JSXBase.HTMLAttributes<HTMLUrPageProfileElement>;
            "ur-profile": LocalJSX.UrProfile & JSXBase.HTMLAttributes<HTMLUrProfileElement>;
            "ur-radio-button": LocalJSX.UrRadioButton & JSXBase.HTMLAttributes<HTMLUrRadioButtonElement>;
            "ur-read-mobile-top-app-bar": LocalJSX.UrReadMobileTopAppBar & JSXBase.HTMLAttributes<HTMLUrReadMobileTopAppBarElement>;
            "ur-segment-button": LocalJSX.UrSegmentButton & JSXBase.HTMLAttributes<HTMLUrSegmentButtonElement>;
            "ur-select": LocalJSX.UrSelect & JSXBase.HTMLAttributes<HTMLUrSelectElement>;
            "ur-switch": LocalJSX.UrSwitch & JSXBase.HTMLAttributes<HTMLUrSwitchElement>;
            "ur-tabs": LocalJSX.UrTabs & JSXBase.HTMLAttributes<HTMLUrTabsElement>;
            "ur-text-field": LocalJSX.UrTextField & JSXBase.HTMLAttributes<HTMLUrTextFieldElement>;
            "ur-top-app-bar": LocalJSX.UrTopAppBar & JSXBase.HTMLAttributes<HTMLUrTopAppBarElement>;
            "ur-user": LocalJSX.UrUser & JSXBase.HTMLAttributes<HTMLUrUserElement>;
            "ur-user-profile": LocalJSX.UrUserProfile & JSXBase.HTMLAttributes<HTMLUrUserProfileElement>;
        }
    }
}
