/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Novl } from "./models/novl";
import { Breakpoints, Grid } from "./data/novl-carousel";
export { Novl } from "./models/novl";
export { Breakpoints, Grid } from "./data/novl-carousel";
export namespace Components {
    interface UrNovl {
        "authorAvatar": any;
        "authorName": any;
        "borderRadius": string;
        "likes": number;
        "novlCover": any;
        "novlCoverFallback": string;
        "novlDescription": any;
        "novlTitle": string;
        "price": string | null;
        "published": boolean;
        "publisherAvatar": string | null;
        "publisherName": string | null;
        "showStats": boolean;
        "views": number;
    }
    interface UrNovlCarousel {
        "breakpoints"?: Breakpoints;
        "grid"?: Grid;
        "novls": Array<Novl>;
        "slidesPerView"?: number | 'auto';
        "spaceBetween"?: number | string;
    }
}
export interface UrNovlCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUrNovlElement;
}
declare global {
    interface HTMLUrNovlElementEventMap {
        "authorClicked": any;
    }
    interface HTMLUrNovlElement extends Components.UrNovl, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUrNovlElementEventMap>(type: K, listener: (this: HTMLUrNovlElement, ev: UrNovlCustomEvent<HTMLUrNovlElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUrNovlElementEventMap>(type: K, listener: (this: HTMLUrNovlElement, ev: UrNovlCustomEvent<HTMLUrNovlElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUrNovlElement: {
        prototype: HTMLUrNovlElement;
        new (): HTMLUrNovlElement;
    };
    interface HTMLUrNovlCarouselElement extends Components.UrNovlCarousel, HTMLStencilElement {
    }
    var HTMLUrNovlCarouselElement: {
        prototype: HTMLUrNovlCarouselElement;
        new (): HTMLUrNovlCarouselElement;
    };
    interface HTMLElementTagNameMap {
        "ur-novl": HTMLUrNovlElement;
        "ur-novl-carousel": HTMLUrNovlCarouselElement;
    }
}
declare namespace LocalJSX {
    interface UrNovl {
        "authorAvatar"?: any;
        "authorName"?: any;
        "borderRadius"?: string;
        "likes"?: number;
        "novlCover"?: any;
        "novlCoverFallback"?: string;
        "novlDescription"?: any;
        "novlTitle"?: string;
        "onAuthorClicked"?: (event: UrNovlCustomEvent<any>) => void;
        "price"?: string | null;
        "published"?: boolean;
        "publisherAvatar"?: string | null;
        "publisherName"?: string | null;
        "showStats"?: boolean;
        "views"?: number;
    }
    interface UrNovlCarousel {
        "breakpoints"?: Breakpoints;
        "grid"?: Grid;
        "novls"?: Array<Novl>;
        "slidesPerView"?: number | 'auto';
        "spaceBetween"?: number | string;
    }
    interface IntrinsicElements {
        "ur-novl": UrNovl;
        "ur-novl-carousel": UrNovlCarousel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ur-novl": LocalJSX.UrNovl & JSXBase.HTMLAttributes<HTMLUrNovlElement>;
            "ur-novl-carousel": LocalJSX.UrNovlCarousel & JSXBase.HTMLAttributes<HTMLUrNovlCarouselElement>;
        }
    }
}
