# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build web components

on: [push]

env:
    CI: true

permissions:
    contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm run build-storybook
      - name: Extract git branch
        run: |
            # Short name for current branch. For PRs, use target branch (base ref)
            GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
            echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
      - run: |
            echo "Current branch $GIT_BRANCH"

            git config user.name "GitHub Actions"
            git config user.email "github-actions@users.noreply.github.com"

            npm version patch --no-git-tag-version

            VERSION="$(cat package.json | jq -r '.version')"

            git status

            git add .

            git commit -m "Release ${VERSION}

            [skip ci]
            "

            git tag ${VERSION}

            git push origin $VERSION
            git push origin $GIT_BRANCH

